## Python for Data Analysis - Chapter 04 - Scripting Questions

### 1. Wtite a program to take name and age fromm the user and print the greeting message?

In [1]:
user_name = input("Enter the user name:")
user_age = input ("Enter your age:")

print ("Welcome {} to ProITBridge and your age {} matching to our company age!".format(user_name,user_age))

Enter the user name: manikandababu
Enter your age: 44

Welcome manikandababu to ProITBridge and your age 44 matching to our company age!

### 2. Create a list of numbers and print only even numbers using for loop

In [2]:
numbers = [1,2,3,4,5,6,7,8,9,10]

for i in numbers:
    if i%2==0:
        print(i)

2
4
6
8
10

In [3]:
numbers=range(1,31)

for i in numbers:
    if i%2==0:
        print (i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30

In [4]:
numbers=range(1,31)

even_numbers = []

for i in numbers:
    if i%2==0:
        even_numbers.append(i)
print (even_numbers)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]

In [5]:
numbers=range(1,21)

even_numbers = []

for i in numbers:
    if i%2==0:
        even_numbers.append(i)
print (even_numbers)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

### 3. Write a program that handles division by zero  using try-except

In [6]:
num = int(input ("Enter the numerator:"))
den = int(input ("Enter the denominator:"))

result = num/den

print (result)

Enter the numerator: 66
Enter the denominator: 5

13.2

In [7]:
num = int(input ("Enter the numerator:"))
den = int(input ("Enter the denominator:"))

try:
    divison = num/den
    print (divison)

except ZeroDivisionError:
        print ("Enter the number greater then zero!")
        print ("Please Try Again!")

Enter the numerator: 56
Enter the denominator: 0

Enter the number greater then zero!
Please Try Again!

### 4. Given a String, count how many vowels it has?

In [24]:
vowels = ["a","e","i","o","u"]

words = []

user_input = str(input("Enter any english word:"))

for i in user_input.lower():
    if i in vowels:
        words.append(i)
print(words)
print ("Vowels count in given word:",len(words))

Enter any english word: conversation

['o', 'e', 'a', 'i', 'o']
Vowels count in given word: 5

### 5. Reverse a list without using built-in reverse functions.

In [9]:
vowels = "manikandababu"[::-1]

print (vowels)

ubabadnakinam

In [10]:
vowels = ["a","e","i","o","u"]
vowels.reverse()
vowels

['u', 'o', 'i', 'e', 'a']

In [11]:
original_list=[1,2,3,4,5]
original_list

[1, 2, 3, 4, 5]

In [12]:
i = len(original_list)-1
i

4

In [13]:
original_list=[1,2,3,4,5]

i = len(original_list)-1

updated_list = []

while i>=0:
    updated_list.append(original_list[i])
    i=i-1
print (updated_list)

[5, 4, 3, 2, 1]

### 6. create a dictionary with atleast 5 Key-value pairs and print them

In [14]:
class_marks ={"English":[60,70,80,90,100],"Tamil":[60,70,80,90,100],"Maths":[60,70,80,90,100],"Science":[60,70,80,90,100],"Social":[60,70,80,90,100]}
class_marks

{'English': [60, 70, 80, 90, 100],
 'Tamil': [60, 70, 80, 90, 100],
 'Maths': [60, 70, 80, 90, 100],
 'Science': [60, 70, 80, 90, 100],
 'Social': [60, 70, 80, 90, 100]}

In [15]:
import pandas as pd

pd.DataFrame(data=class_marks)

   English  Tamil  Maths  Science  Social
0       60     60     60       60      60
1       70     70     70       70      70
2       80     80     80       80      80
3       90     90     90       90      90
4      100    100    100      100     100

### 7. Write a Pandas code to read csv file and print the top 5 rows

In [16]:
salary_data = pd.read_csv("employee_data.csv")
salary_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [17]:
salary_data.head()

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024

### 8. Creata a DataFramae from a Python Dictionay

In [18]:
class_marks ={"English":[60,70,80,90,100],"Tamil":[60,70,80,90,100],"Maths":[60,70,80,90,100],"Science":[60,70,80,90,100],"Social":[60,70,80,90,100]}
class_marks

{'English': [60, 70, 80, 90, 100],
 'Tamil': [60, 70, 80, 90, 100],
 'Maths': [60, 70, 80, 90, 100],
 'Science': [60, 70, 80, 90, 100],
 'Social': [60, 70, 80, 90, 100]}

In [19]:
pd.DataFrame(data=class_marks)

   English  Tamil  Maths  Science  Social
0       60     60     60       60      60
1       70     70     70       70      70
2       80     80     80       80      80
3       90     90     90       90      90
4      100    100    100      100     100

### 9. Replace all missing values in a DataFrame with the columns mean

In [20]:
salary_data = pd.read_csv("employee_data.csv")
salary_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [21]:
mean = salary_data["Salary"].mean()
mean

np.float64(62500.0)

In [22]:
salary_data["Salary"].fillna(value=salary_data["Salary"].mean(),inplace=True)

C:\Users\manik\AppData\Local\Temp\ipykernel_17012\2911663248.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  salary_data["Salary"].fillna(value=salary_data["Salary"].mean(),inplace=True)

In [23]:
salary_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62500.0  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech  62500.0  12-11-2020

### 10. Filter rows in a DataFrame where the "Age" column is greater than 30

In [25]:
salary_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62500.0  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech  62500.0  12-11-2020

In [26]:
salary_data["Age"]>30

0    False
1     True
2    False
3    False
4    False
5     True
6     True
7     True
Name: Age, dtype: bool

In [27]:
salary_data[salary_data["Age"]>30]

    Name   Age Department   Salary   Join_Date
1  Nasir  31.0    IT Tech  62500.0  12-11-2020
5  Navin  35.0    Support  72000.0  19-08-2023
6    NaN  40.0         IT  64000.0  10-09-2022
7  Nasir  31.0    IT Tech  62500.0  12-11-2020