## Python Data Structures - Chapter 02 - TASK list

##  TASK 01
### 1. List Functions  
### it contains Total 10 functions, as will see with one example for each function below

In [8]:
### 1.1 Index function: (it returns the index of the first matched item from the list)

student_mark = [50,60,70,80,90,100,110,70]

student_mark.index(70)

2

In [15]:
### 1.2 Append function:  (it adds an item at the end of the list)

fruits = ["Apple","Orange","Banana","Cucumber"]
fruits

['Apple', 'Orange', 'Banana', 'Cucumber']

In [16]:
fruits.append("pepsi")
fruits

['Apple', 'Orange', 'Banana', 'Cucumber', 'pepsi']

In [23]:
### 1.3 Extend function:(adding multiple elemnts given in a list to another list)

fruits = ["Apple","Orange","Banana","Cucumber"]
soft_drinks=["coke","fanta","campa"]

fruits
soft_drinks

['coke', 'fanta', 'campa']

In [24]:
fruits.extend(soft_drinks)
fruits

['Apple', 'Orange', 'Banana', 'Cucumber', 'coke', 'fanta', 'campa']

In [25]:
### 1.4 insert function: (it inserts a itemm to a given index postition into the list)

fruits = ["Apple","Orange","Banana","Cucumber"]

fruits.insert(2,"coke")
fruits

['Apple', 'Orange', 'coke', 'Banana', 'Cucumber']

In [29]:
#### 1.5 Pop function: (it used to remove an item to a given index position in the lost)

fruits = ["Apple","Orange","Banana","Cucumber","coke"]

fruits.pop(4)
fruits

['Apple', 'Orange', 'Banana', 'Cucumber']

In [30]:
### 1.6 Remove function: (it moved the first occurance of the given item in the list)

marks = [50,60,70,80,90,50]
marks

[50, 60, 70, 80, 90, 50]

In [31]:
marks.remove(50)
marks

[60, 70, 80, 90, 50]

In [32]:
### 1.7 Clear function: (it clear/delete all the items inside the given list)

marks_list = [50,60,70,80,90,100,110]
marks_list

[50, 60, 70, 80, 90, 100, 110]

In [33]:
marks_list.clear()
marks_list

[]

In [34]:
### 1.8 Count function: (it returns the count of the item given in the list and the given item not in the list, returns ZERO)

marks_english = [50,60,70,80,90,100,110,50,50,50]
marks_english

[50, 60, 70, 80, 90, 100, 110, 50, 50, 50]

In [35]:
marks_english.count(50)

4

In [36]:
marks_english.count(200)

0

In [37]:
### 1.9 Reverse function: (it return the items given inside the list in reverse order)

fruits = ["Apple","orange","kiwi","watermelon","mango"]
fruits

['Apple', 'orange', 'kiwi', 'watermelon', 'mango']

In [38]:
fruits.reverse()
fruits

['mango', 'watermelon', 'kiwi', 'orange', 'Apple']

In [39]:
### 1.10 Sort function: (it sort the items given inside the list in ascending order)

fruits = ['mango', 'watermelon', 'kiwi', 'orange', 'Apple']
fruits

['mango', 'watermelon', 'kiwi', 'orange', 'Apple']

In [41]:
fruits.sort()
fruits

['Apple', 'kiwi', 'mango', 'orange', 'watermelon']

## 2. Tuples Functions

### it contains Total 2 functions (Index and Count), as will see with one example for each function below

In [45]:
### 2.1. Count Function - (returns the count of the item in the given tuple)

marks_english = (50,60,70,80,90,100,110,50,50,50)
marks_english

(50, 60, 70, 80, 90, 100, 110, 50, 50, 50)

In [46]:
type(marks_english)

tuple

In [50]:
marks_english.count(50)

4

In [51]:
### 2.2 Index Function - (returns the index position for the given item inside a tupe)

marks_english = (50,60,70,80,90,100,110,50,50,50)

In [52]:
marks_english.index(60)

1

In [53]:
marks_english.index(90)

4

In [54]:
marks_english.index(50)

0

## 3. Set Function

### it contains Total 17 functions (Index and Count), as will see with one example for each function below

In [56]:
### 3.1 ADD function - (Adds an element to the set)

fruits = {"Apple","orange","kiwi","watermelon"}
fruits

{'Apple', 'kiwi', 'orange', 'watermelon'}

In [57]:
type(fruits)

set

In [58]:
fruits.add("Mango")
fruits

{'Apple', 'Mango', 'kiwi', 'orange', 'watermelon'}

In [59]:
### 3.2 CLEAR function - (Removes all the elements from the set)

marks_english = {50,60,70,80,90,100,110,50,50,50}
marks_english

{50, 60, 70, 80, 90, 100, 110}

In [60]:
marks_english.clear()
marks_english

set()

In [61]:
### 3.3 COPY Function - (Returns a copy of the set)

fruits = {"Apple","orange","kiwi","watermelon"}
fruits

{'Apple', 'kiwi', 'orange', 'watermelon'}

In [62]:
fruits.copy()
fruits

{'Apple', 'kiwi', 'orange', 'watermelon'}

In [63]:
### 3.4 Difference Function - (Returns a set containing the difference between two or more sets)

fruits_shop = {"Apple","orange","kiwi","watermelon"}
fruits_home = {"Banana","Pomogranate","Apple"}

fruits_shop

{'Apple', 'kiwi', 'orange', 'watermelon'}

In [64]:
fruits_home

{'Apple', 'Banana', 'Pomogranate'}

In [65]:
fruits_shop.difference(fruits_home)

{'kiwi', 'orange', 'watermelon'}

In [66]:
fruits_home.difference(fruits_shop)

{'Banana', 'Pomogranate'}

In [67]:
### 3.5 Difference_update function - (Removes the items in this set that are also included in another, specified set)

### The difference_update() method is different from the difference() method, because the difference() method returns a new set, without the unwanted items, 
### and the difference_update() method removes the unwanted items from the original set.

In [68]:
fruits_home = {"Apple","orange","kiwi","watermelon"}
fruits_shop = {"Banana","Pomogranate","Apple"}

fruits_home.difference_update(fruits_shop)

In [69]:
fruits_home

{'kiwi', 'orange', 'watermelon'}

In [70]:
fruits_shop

{'Apple', 'Banana', 'Pomogranate'}

In [71]:
### 3.6 Discard function - (Remove the specified item)

fruits_home = {"Apple","orange","kiwi","watermelon"}
fruits_home

{'Apple', 'kiwi', 'orange', 'watermelon'}

In [73]:
fruits_home.discard("Apple")
fruits_home

{'kiwi', 'orange', 'watermelon'}

In [74]:
### 3.7 Intersection function - (Returns a set, that is the intersection of two other sets)/ Returns the common item between the given sets


fruits_home = {"Apple","orange","kiwi","watermelon"}
fruits_shop = {"Banana","Pomogranate","Apple"}

fruits_home

{'Apple', 'kiwi', 'orange', 'watermelon'}

In [75]:
fruits_shop

{'Apple', 'Banana', 'Pomogranate'}

In [76]:
fruits_home.intersection(fruits_shop)

{'Apple'}

In [77]:
### 3.8 Intersection_update  function - (Removes the items in this set that are not present in other, specified set(s))

fruits_home = {"Apple","orange","kiwi","watermelon"}
fruits_shop = {"Banana","Pomogranate","Apple"}

fruits_home

{'Apple', 'kiwi', 'orange', 'watermelon'}

In [78]:
fruits_shop

{'Apple', 'Banana', 'Pomogranate'}

In [79]:
fruits_home.intersection_update(fruits_shop)

In [80]:
fruits_home

{'Apple'}

In [81]:
### 3.9 Isdisjoint function - (Returns whether two sets have a intersection (common items) or not)

mobiles = {"Iphone","Samsung","Moto","Redmi"}
laptop  = {"lenovo", "Asus","HP","Dell"}

mobiles

{'Iphone', 'Moto', 'Redmi', 'Samsung'}

In [82]:
laptop

{'Asus', 'Dell', 'HP', 'lenovo'}

In [83]:
mobiles.isdisjoint(laptop)        ### belos retuns as "true" - NO common items between 02 sets

True

In [85]:
### 3.10 Issubset function - (Returns True if all items of this set is present in another set}

thinkpad  = {"lenovo", "Asus","HP","Dell"}
mobile  = {"Dell", "lenovo","Asus","HP"}

thinkpad

{'Asus', 'Dell', 'HP', 'lenovo'}

In [86]:
mobile

{'Asus', 'Dell', 'HP', 'lenovo'}

In [87]:
thinkpad.issubset(mobile)                         ## items in both the sets are matching each other.

True

In [88]:
### 3.11 Issuperset function - (Returns True if all items of another set is present in this set)

thinkpad  = {"lenovo", "Asus"}
mobile  = {"Dell", "lenovo","Asus","HP"}

thinkpad

{'Asus', 'lenovo'}

In [89]:
mobile

{'Asus', 'Dell', 'HP', 'lenovo'}

In [90]:
thinkpad.issuperset(mobile)

False

In [91]:
mobile.issuperset(thinkpad)

True

In [92]:
### 3.12 Pop Function - (Removes an random element from the set)

fruits = {"Apple","Orange","Banana","Cucumber","coke"}
fruits

{'Apple', 'Banana', 'Cucumber', 'Orange', 'coke'}

In [95]:
fruits.pop()

'Apple'

In [96]:
fruits

{'Banana', 'Cucumber', 'Orange', 'coke'}

In [97]:
fruits.pop()

'coke'

In [98]:
fruits

{'Banana', 'Cucumber', 'Orange'}

In [99]:
### 3.13 Remove function - (Removes the specified element)

fruits = {"Apple","Orange","Banana","Cucumber","coke"}
fruits

{'Apple', 'Banana', 'Cucumber', 'Orange', 'coke'}

In [100]:
fruits.remove("coke")
fruits

{'Apple', 'Banana', 'Cucumber', 'Orange'}

In [101]:
### 3.14 Union Function - (Return a set that contains all items from both sets, duplicates)

thinkpad  = {"lenovo", "Asus"}
mobile  = {"Dell", "lenovo","Asus","HP"}

thinkpad

{'Asus', 'lenovo'}

In [102]:
mobile

{'Asus', 'Dell', 'HP', 'lenovo'}

In [103]:
mobile.union(thinkpad)

{'Asus', 'Dell', 'HP', 'lenovo'}

In [104]:
thinkpad  = {"lenovo", "Asus"}
fruits = {"Apple","Orange","Banana","Cucumber","coke"}

thinkpad.union(fruits)

{'Apple', 'Asus', 'Banana', 'Cucumber', 'Orange', 'coke', 'lenovo'}

In [105]:
### 3.15 Update Function - (Update the set with the union of this set and others)
### updates the current set, by adding items from another set 

thinkpad  = {"lenovo", "Asus"}
fruits = {"Apple","Orange","Banana","Cucumber","coke"}

thinkpad.update(fruits)

In [106]:
thinkpad

{'Apple', 'Asus', 'Banana', 'Cucumber', 'Orange', 'coke', 'lenovo'}

In [107]:
thinkpad  = {"lenovo", "Asus"}
mobile  = {"Dell", "lenovo","Asus","HP"}

thinkpad

{'Asus', 'lenovo'}

In [108]:
thinkpad.update(mobile)

In [109]:
thinkpad

{'Asus', 'Dell', 'HP', 'lenovo'}

In [110]:
### 3.16 Symmetric Difference - (Returns a set with the symmetric differences of two sets)
### Return a set that contains all items from both sets, except items that are present in both sets:

fruits_home = {"Apple","orange","kiwi","watermelon"}
fruits_shop = {"Banana","Pomogranate","Apple"}

fruits_home

{'Apple', 'kiwi', 'orange', 'watermelon'}

In [111]:
fruits_shop

{'Apple', 'Banana', 'Pomogranate'}

In [112]:
fruits_home.symmetric_difference(fruits_shop)

{'Banana', 'Pomogranate', 'kiwi', 'orange', 'watermelon'}

In [117]:
### 3.17 Symmetric Difference update - Inserts the symmetric differences from this set and another
### Remove the items that are present in both sets, AND insert the items that is not present in both sets:

fruits_home = {"Apple","orange","kiwi","watermelon"}
fruits_shop = {"Banana","Pomogranate","Apple","kiwi"}

fruits_home

{'Apple', 'kiwi', 'orange', 'watermelon'}

In [118]:
fruits_shop

{'Apple', 'Banana', 'Pomogranate', 'kiwi'}

In [119]:
fruits_home.symmetric_difference_update(fruits_shop)

In [120]:
fruits_home

{'Banana', 'Pomogranate', 'orange', 'watermelon'}

## 4. Dictionaries 

### it contains Total 11 functions (Index and Count), as will see with one example for each function below

In [123]:
### 4.1 Clear function - (Removes all the elements from the dictionary)

marks = {"English":80,"Tamil":90,"Mathis":100}
marks

{'English': 80, 'Tamil': 90, 'Mathis': 100}

In [124]:
marks.clear()

In [125]:
marks

{}

In [126]:
### 4.2 Copy function - (Returns a copy of the dictionary)

marks = {"English":80,"Tamil":90,"Mathis":100}
marks

{'English': 80, 'Tamil': 90, 'Mathis': 100}

In [127]:
marks.copy()

{'English': 80, 'Tamil': 90, 'Mathis': 100}

In [132]:
### 4.3 fromkeys() function - Returns a dictionary with the specified given  keys and value seperately)

subject = {"English","Tamil","Maths"}
marks = 80

subject_marks = dict.fromkeys(subject,marks)

subject_marks

{'English': 80, 'Maths': 80, 'Tamil': 80}

In [137]:
### 4.4 get function - (Returns the value of the specified key)

marks = {"English":80,"Tamil":90,"Maths":100}
marks

{'English': 80, 'Tamil': 90, 'Maths': 100}

In [138]:
marks.get("Tamil")

90

In [139]:
marks.get("Maths")

100

In [140]:
### 4.5 item function = (Returns a list containing a tuple for each key value pair)

marks = {"English":80,"Tamil":90,"Maths":100}
marks

{'English': 80, 'Tamil': 90, 'Maths': 100}

In [141]:
marks.items()

dict_items([('English', 80), ('Tamil', 90), ('Maths', 100)])

In [142]:
### 4.6 Keys() function - (Returns a list containing the dictionary's keys)

marks = {"English":80,"Tamil":90,"Maths":100}
marks

{'English': 80, 'Tamil': 90, 'Maths': 100}

In [143]:
marks.keys()

dict_keys(['English', 'Tamil', 'Maths'])

In [144]:
### 4.7 Value function - (	Returns a list of all the values in the dictionary)

marks = {"English":80,"Tamil":90,"Maths":100}
marks

{'English': 80, 'Tamil': 90, 'Maths': 100}

In [145]:
marks.values()

dict_values([80, 90, 100])

In [148]:
### 4.8 Pop Function - (Removes the element with the specified key)

car = {"brand": "Ford","model": "Mustang","year": 1964}
car

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

In [149]:
car.pop('model')

'Mustang'

In [154]:
### 4.9 popitem() function - (Remove the last item from the dictionary)

car = {"brand": "Ford","model": "Mustang","year": 1964}
car

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

In [155]:
car.popitem()

('year', 1964)

In [156]:
car

{'brand': 'Ford', 'model': 'Mustang'}

In [157]:
### 4.10 Update function - (Updates the dictionary with the specified key-value pairs)

car = {"brand": "Ford","model": "Mustang","year": 1964}
car

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

In [161]:
car.update({"Drink":"Pepsi"})

In [162]:
car

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'Drink': 'Pepsi'}

In [163]:
### 4.11 setdefault() function - (Returns the value of the specified key. If the key does not exist: insert the key, with the specified value)

car = {"brand": "Ford","model": "Mustang","year": 1964}
car

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

In [167]:
car.setdefault("color","Red")

'Red'

In [168]:
car

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'Red'}

## TASK 02
### Create 03 DataFrames using Dictoniaries

In [171]:
## DataFrame 01:

english_marks = {"English":[65,70,75,83,85]}
english_marks

{'English': [65, 70, 75, 83, 85]}

In [172]:
import pandas as pd

pd.DataFrame(data=english_marks)

   English
0       65
1       70
2       75
3       83
4       85

In [173]:
## DataFrame 02:

subject_marks = {"English":[65,70,75,83,85],"Tamil":[63,73,43,83,53],"Maths":[44,54,64,74,84]}
subject_marks

{'English': [65, 70, 75, 83, 85],
 'Tamil': [63, 73, 43, 83, 53],
 'Maths': [44, 54, 64, 74, 84]}

In [174]:
pd.DataFrame(data=subject_marks)

   English  Tamil  Maths
0       65     63     44
1       70     73     54
2       75     43     64
3       83     83     74
4       85     53     84

In [175]:
## DataFrame 03:

class_marks = {"Student Name":["Arya","Honeesha","Kavya","Veda","Raghav"],"English":[65,70,75,83,85],"Tamil":[63,73,43,83,53],"Maths":[44,54,64,74,84]}
class_marks

{'Student Name': ['Arya', 'Honeesha', 'Kavya', 'Veda', 'Raghav'],
 'English': [65, 70, 75, 83, 85],
 'Tamil': [63, 73, 43, 83, 53],
 'Maths': [44, 54, 64, 74, 84]}

In [176]:
pd.DataFrame(data=class_marks)

  Student Name  English  Tamil  Maths
0         Arya       65     63     44
1     Honeesha       70     73     54
2        Kavya       75     43     64
3         Veda       83     83     74
4       Raghav       85     53     84